### ISSUE TITLE
not working with Disney+

### ISSUE THREAD

**Issue by theTobster500** [sabaatworld/HyperionScreenCap#65]
the Disney+ app has some form of copyright protection it seems, the video section of the screen is just black. any way to work around that?

**Comment by Xitee1** [comment]
It works if you watch Disney+ in Firefox. However your quality will be limited to 720p.
The only way to watch 1080p or above is using the Hardware setup with an HDMI splitter. It will also work in the App but even then your quality could get limited because there is some technology that checks if there is anything in between the wiring of your PC and monitor.

**Comment by theTobster500** [comment]
turns out it works now that I have an amd card (5700 xt). on my gtx 1060 it didn't work but now it does. not sure what's different about it, probably the way nvidia handles screen recording compared to amd. works consistently though
